<?php

namespace AppBundle\Repository;

/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLastDestinations()
    {

        $query = $this->createQueryBuilder('d')
            ->orderBy('d.start', 'DESC')
            ->setMaxResults('3')
            ->getQuery();

        return $query->getResult();
    }
}
